version: '3.7'
services:
  caddy:
    build: .
    ports:
      - "80:80"
      - "443:443"
      - "2019:2019"
    volumes:
      - ./website:/usr/share/caddy
      - ./logs:/var/log/caddy
      - target: /data
        tmpfs:
          size: 12000
        type: tmpfs